### ISSUE TITLE
Single quote issue

### ISSUE THREAD

**Issue by samratchak** [speedovation/kiwi#210] opened 2016-04-27 18:36 UTC
Typing a single quote (') introduces a second quote, which is fine. But it is not intelligent enough to see that a start quote already exists and deleting the quote also deletes the second quote which was automatically introduced. It is annoying and doesn't conform to standard practices. Needs fixing.

**Comment by codeyash** [comment] 2016-04-28 07:19
Its not a bug but feature. Try to space in b/w and delete chars or simply use delete button.

All famous follows same way. Please study and suggest how exactly you want it.

**Comment by codeyash** [comment] 2016-04-28 07:56
Plus you can turn off using settings :) Open preferences from option menu. Click on first option of right side of opened dialog if not already selected. Uncheck it. That's it.

**Comment by codeyash** [comment] 2016-05-05 14:12
For now I'm closing. Please propose best solution to get it work. We may try to implement that.

**Closed as completed by codeyash** 2016-05-05 14:12 UTC
Labels: help wanted
